spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    web:
      pageble:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true

  security:
    user:
      name: admin
      password: admin
      roles: ROLE_ADMIN
